### ISSUE TITLE
安装时报错no `ClipboardType` in `clipboard`

### ISSUE THREAD

**Issue by liangz678** [erasin/hx-lsp#1]
error[E0432]: unresolved import `super::ClipboardType`
   --> C:\Users\Administrator\.cargo\registry\src\rsproxy.cn-0dccff568467c15b\hx-lsp-0.1.0\src\clipboard.rs:345:36
    |
345 |     use super::{ClipboardProvider, ClipboardType};
    |                                    ^^^^^^^^^^^^^ no `ClipboardType` in `clipboard`

For more information about this error, try `rustc --explain E0432`.
error: could not compile `hx-lsp` (lib) due to 1 previous error
error: failed to compile `hx-lsp v0.1.0`, intermediate artifacts can be found at `C:\Users\Administrator\AppData\Local\Temp\cargo-installrA7Wke`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.

**Comment by erasin** [comment]
已处理
移除 window 代码的 ClipboardType，
追加了 github actions 检查。
添加了window下的检查，linux 下交叉编译 window 已测试。

**Comment by erasin** [comment]
修改使用 copypasta 处理剪贴板，我没有window，无法测试。

**Comment by erasin** [comment]
windows 的版本发行了，https://github.com/erasin/hx-lsp/releases

另外，我自己使用自用版本的helix也提供了 https://github.com/erasin/helix/releases ,说明请看 https://github.com/erasin/helix-config
