### ISSUE TITLE
Does not work on Linux

### ISSUE THREAD

**Issue by ZakharEl** [erasin/hx-lsp#2]
Does not work on linux. I have tried this with both package manager version of helix and compilesd from source version of helix. I have tried both master branch and snippet_placeholder branch for helix being compiled from source.

**Comment by erasin** [comment]
This is my helix branch [erasin/helix/local-dev](https://github.com/erasin/helix/tree/local-dev) and config files [erasin/helix-config](https://github.com/erasin/helix-config) that I has use these with archlinux.

The `hx-lsp` work with helix [snippet_placeholder #9801](https://github.com/helix-editor/helix/pull/9801).

**Comment by ZakharEl** [comment]
Nevermind. It works, however themes do not work with the snippet_placeholder branch. Do not know why the functionality for tabstops, etc is working now whereas it was not working before.
